using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using EntityLayer.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Documents;
using System.Windows.Media;
using System.Windows.Xps.Packaging;

namespace WPFLayer {
    public enum ExportFormat { Xps, Docx }

    public static class ReportBuilder {
        private const double A4W = 793;   // 96 DPI
        private const double A4H = 1122;  // 96 DPI

        public static void PrepareDocumentForA4(FlowDocument doc) {
            doc.PageWidth = A4W;
            doc.PageHeight = A4H;
            doc.ColumnWidth = doc.PageWidth;
        }

        public static FlowDocument BuildReportDocument(StatisticsSummary s, DateTime from, DateTime to, string generatedBy) {
            PrepareNulls(s);

            var doc = new FlowDocument {
                PagePadding = new Thickness(40),
                FontFamily = new FontFamily("Segoe UI"),
                FontSize = 12
            };
            PrepareDocumentForA4(doc);

            doc.Blocks.Add(Title("Statistics Report"));
            doc.Blocks.Add(Muted(string.Format("Period: {0:dd.MM.yyyy} – {1:dd.MM.yyyy}", from, to)));
            doc.Blocks.Add(Muted(string.Format("Generated by: {0}   •   Generated at: {1:dd.MM.yyyy HH:mm}", generatedBy, DateTime.Now)));

            doc.Blocks.Add(Section("Overview"));
            doc.Blocks.Add(KpiTable(s));

            doc.Blocks.Add(Section("Top Suppliers"));
            doc.Blocks.Add(BreakdownTable(s.TopSuppliers));

            doc.Blocks.Add(Section("Top Products (Export)"));
            doc.Blocks.Add(BreakdownTable(s.TopProductsExport));

            doc.Blocks.Add(Section("Recent Transactions"));
            doc.Blocks.Add(TransactionsTable(s.Activity));

            return doc;
        }

        public static void ExportReport(FlowDocument doc, string path, ExportFormat format) {
            PrepareDocumentForA4(doc);

            switch (format) {
                case ExportFormat.Xps:
                    SaveFlowDocumentAsXps(doc, path);
                    break;
                case ExportFormat.Docx:
                    SaveFlowDocumentAsDocx(doc, path);
                    break;
                default:
                    throw new ArgumentOutOfRangeException("format");
            }
        }

        // XPS

        public static void SaveFlowDocumentAsXps(FlowDocument doc, string path) {
            var paginator = ((IDocumentPaginatorSource)doc).DocumentPaginator;
            using (var xps = new XpsDocument(path, FileAccess.Write)) {
                var writer = XpsDocument.CreateXpsDocumentWriter(xps);
                writer.Write(paginator);
            }
        }

        // DOCX

        public static void SaveFlowDocumentAsDocx(FlowDocument doc, string path) {
            using (var pkg = WordprocessingDocument.Create(path, WordprocessingDocumentType.Document)) {
                var main = pkg.AddMainDocumentPart();
                main.Document = new DocumentFormat.OpenXml.Wordprocessing.Document(
                    new DocumentFormat.OpenXml.Wordprocessing.Body()
                );

                var body = main.Document.Body;

                foreach (var block in doc.Blocks) {
                    var p = block as System.Windows.Documents.Paragraph;
                    if (p != null) { body.Append(ToDocxParagraph(p)); continue; }

                    var t = block as System.Windows.Documents.Table;
                    if (t != null) { body.Append(ToDocxTable(t)); continue; }
                }

                main.Document.Save();
            }
        }

        private static DocumentFormat.OpenXml.Wordprocessing.Paragraph ToDocxParagraph(System.Windows.Documents.Paragraph p) {
            var text = string.Concat(p.Inlines.OfType<System.Windows.Documents.Run>().Select(r => r.Text ?? ""));

            var para = new DocumentFormat.OpenXml.Wordprocessing.Paragraph();
            var run = new DocumentFormat.OpenXml.Wordprocessing.Run(
                new DocumentFormat.OpenXml.Wordprocessing.Text(text) {
                    Space = DocumentFormat.OpenXml.SpaceProcessingModeValues.Preserve
                }
            );

            if (p.FontWeight == FontWeights.Bold || p.FontWeight == FontWeights.SemiBold) {
                run.RunProperties = new DocumentFormat.OpenXml.Wordprocessing.RunProperties(
                    new DocumentFormat.OpenXml.Wordprocessing.Bold()
                );
            }

            if (p.FontSize > 0) {
                para.ParagraphProperties = new DocumentFormat.OpenXml.Wordprocessing.ParagraphProperties(
                    new DocumentFormat.OpenXml.Wordprocessing.ParagraphMarkRunProperties(
                        new DocumentFormat.OpenXml.Wordprocessing.FontSize { Val = ((int)(p.FontSize * 2)).ToString() }
                    )
                );
            }

            para.Append(run);
            return para;
        }

        private static DocumentFormat.OpenXml.Wordprocessing.Table ToDocxTable(System.Windows.Documents.Table wpfTable) {
            var tbl = new DocumentFormat.OpenXml.Wordprocessing.Table();
            tbl.AppendChild(new DocumentFormat.OpenXml.Wordprocessing.TableProperties(
                new DocumentFormat.OpenXml.Wordprocessing.TableWidth {
                    Type = DocumentFormat.OpenXml.Wordprocessing.TableWidthUnitValues.Auto
                }
            ));

            foreach (var rg in wpfTable.RowGroups) {
                foreach (var r in rg.Rows) {
                    var row = new DocumentFormat.OpenXml.Wordprocessing.TableRow();

                    foreach (var c in r.Cells) {
                        var cellText = string.Concat(
                            c.Blocks.OfType<System.Windows.Documents.Paragraph>()
                             .SelectMany(pp => pp.Inlines.OfType<System.Windows.Documents.Run>())
                             .Select(rr => rr.Text ?? "")
                        );

                        var cell = new DocumentFormat.OpenXml.Wordprocessing.TableCell();
                        cell.Append(new DocumentFormat.OpenXml.Wordprocessing.Paragraph(
                            new DocumentFormat.OpenXml.Wordprocessing.Run(
                                new DocumentFormat.OpenXml.Wordprocessing.Text(cellText) {
                                    Space = DocumentFormat.OpenXml.SpaceProcessingModeValues.Preserve
                                }
                            )
                        ));

                        cell.Append(new DocumentFormat.OpenXml.Wordprocessing.TableCellProperties(
                            new DocumentFormat.OpenXml.Wordprocessing.TableCellWidth {
                                Type = DocumentFormat.OpenXml.Wordprocessing.TableWidthUnitValues.Auto
                            }
                        ));

                        row.Append(cell);
                    }

                    tbl.Append(row);
                }
            }

            return tbl;
        }

        // WPF

        private static System.Windows.Documents.Paragraph Title(string text) {
            return new System.Windows.Documents.Paragraph(new System.Windows.Documents.Run(text)) {
                FontSize = 24,
                FontWeight = FontWeights.SemiBold,
                Margin = new Thickness(0, 0, 0, 6)
            };
        }

        private static System.Windows.Documents.Paragraph Section(string text) {
            return new System.Windows.Documents.Paragraph(new System.Windows.Documents.Run(text)) {
                FontSize = 16,
                FontWeight = FontWeights.SemiBold,
                Margin = new Thickness(0, 18, 0, 8)
            };
        }

        private static System.Windows.Documents.Paragraph Muted(string text) {
            return new System.Windows.Documents.Paragraph(new System.Windows.Documents.Run(text)) {
                Foreground = Brushes.Gray,
                Margin = new Thickness(0, 0, 0, 2)
            };
        }

        private static System.Windows.Documents.TableRow HeaderRow(params string[] cells) {
            var row = new System.Windows.Documents.TableRow {
                FontWeight = FontWeights.SemiBold,
                Background = Brushes.Gainsboro
            };
            foreach (var c in cells) row.Cells.Add(WpfCell(c));
            return row;
        }

        private static System.Windows.Documents.TableRow Row(params string[] cells) {
            var row = new System.Windows.Documents.TableRow();
            foreach (var c in cells) row.Cells.Add(WpfCell(c));
            return row;
        }

        private static System.Windows.Documents.TableCell WpfCell(string text) {
            var p = new System.Windows.Documents.Paragraph(new System.Windows.Documents.Run(text ?? "")) {
                Margin = new Thickness(0)
            };

            return new System.Windows.Documents.TableCell(p) {
                Padding = new Thickness(6),
                BorderThickness = new Thickness(0.5),
                BorderBrush = Brushes.LightGray
            };
        }

        private static System.Windows.Documents.Table KpiTable(StatisticsSummary s) {
            var t = new System.Windows.Documents.Table { CellSpacing = 0 };
            t.Columns.Add(new System.Windows.Documents.TableColumn { Width = new GridLength(260) });
            t.Columns.Add(new System.Windows.Documents.TableColumn { Width = new GridLength(160) });

            var rg = new System.Windows.Documents.TableRowGroup();
            t.RowGroups.Add(rg);

            rg.Rows.Add(HeaderRow("Metric", "Value"));
            rg.Rows.Add(Row("Total Orders", s.TotalOrders.ToString()));
            rg.Rows.Add(Row("Incoming Units", s.IncomingUnits.ToString()));
            rg.Rows.Add(Row("Outgoing Units", s.OutgoingUnits.ToString()));
            rg.Rows.Add(Row("Avg Lead Time (days)", s.AvgLeadTimeDays.ToString("0.0")));
            rg.Rows.Add(Row("Low Stock Items", s.LowStockCount.ToString()));

            return t;
        }

        private static System.Windows.Documents.Table BreakdownTable(IEnumerable<BreakdownRow> rows) {
            if (rows == null) rows = Enumerable.Empty<BreakdownRow>();

            var t = new System.Windows.Documents.Table { CellSpacing = 0 };
            t.Columns.Add(new System.Windows.Documents.TableColumn { Width = new GridLength(320) });
            t.Columns.Add(new System.Windows.Documents.TableColumn { Width = new GridLength(90) });
            t.Columns.Add(new System.Windows.Documents.TableColumn { Width = new GridLength(90) });

            var rg = new System.Windows.Documents.TableRowGroup();
            t.RowGroups.Add(rg);

            rg.Rows.Add(HeaderRow("Name", "Value", "%"));

            if (!rows.Any()) {
                rg.Rows.Add(Row("(no data)", "", ""));
                return t;
            }

            foreach (var r in rows) {
                rg.Rows.Add(Row(r.Name, r.Value.ToString(), r.Percent.ToString("0.0")));
            }

            return t;
        }

        private static System.Windows.Documents.Table TransactionsTable(IEnumerable<ActivityRow> rows) {
            if (rows == null) rows = Enumerable.Empty<ActivityRow>();

            var t = new System.Windows.Documents.Table { CellSpacing = 0 };
            t.Columns.Add(new System.Windows.Documents.TableColumn { Width = new GridLength(120) });
            t.Columns.Add(new System.Windows.Documents.TableColumn { Width = new GridLength(90) });
            t.Columns.Add(new System.Windows.Documents.TableColumn { Width = new GridLength(200) });
            t.Columns.Add(new System.Windows.Documents.TableColumn { Width = new GridLength(70) });

            var rg = new System.Windows.Documents.TableRowGroup();
            t.RowGroups.Add(rg);

            rg.Rows.Add(HeaderRow("Time", "Type", "Product", "Qty"));

            var list = rows.OrderByDescending(x => x.CreatedAt).Take(20).ToList();
            if (list.Count == 0) {
                rg.Rows.Add(Row("(no transactions)", "", "", ""));
                return t;
            }

            foreach (var r in list) {
                rg.Rows.Add(Row(
                    r.CreatedAt.ToString("dd.MM.yyyy HH:mm"),
                    r.Type ?? "",
                    r.ProductName ?? "",
                    r.QuantityDelta.ToString()
                ));
            }

            return t;
        }

        private static void PrepareNulls(StatisticsSummary s) {
            if (s.TopSuppliers == null) s.TopSuppliers = new List<BreakdownRow>();
            if (s.TopProductsExport == null) s.TopProductsExport = new List<BreakdownRow>();
            if (s.IncomingByDayByProduct == null) s.IncomingByDayByProduct = new List<DailyProductQty>();
            if (s.OutgoingByDayByProduct == null) s.OutgoingByDayByProduct = new List<DailyProductQty>();
            if (s.Activity == null) s.Activity = new List<ActivityRow>();
        }
    }
}
